### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by empiregeneral** [colddew/jtester#1]
编译jtester 1.10.0时出现fitlibrary.batch.trinidad错误，fitlibrary这个类文件在哪里？

**Comment by colddew** [comment]
```
<dependency>
    <groupId>org.fitnesse</groupId>
	<artifactId>fitnesse</artifactId>
	<version>20100211</version>
</dependency>
```

在这个依赖项里，搜了下maven中央仓库，这个版本好像被拿掉了。你可以改成时间比较近的版本，比如：20111025，尝试如果不行可以丢个邮件给我，我可以邮件转发给你这个20100211版本的jar包，你自行添加到本地仓库里或者nexus里

![image](https://user-images.githubusercontent.com/6032545/63767908-7107d600-c901-11e9-8e30-f175611c1aec.png)

**Comment by empiregeneral** [comment]
这个似乎不是主要的，提示报错是缺乏fitlibrary.batch.trinidad类对应的包，该包不知道是什么版本。
我的邮箱是13777470884@qq.com

**Comment by colddew** [comment]
![image](https://user-images.githubusercontent.com/6032545/63825131-1ebfc700-c98c-11e9-9e8e-eb925500cdf3.png)


就是我之前提到的依赖项，jar包已经发你邮箱了
